import uturtle

turtle = uturtle.Turtle()

def rect(x, y, color, x2, y2):
    width = abs(x2 - x)
    height = abs(y2 - y)
    turtle.pencolor(color)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.fillcolor(color)
    # turtle.color(color, color)
    turtle.begin_fill()
    turtle.fd(width)
    turtle.right(90)
    turtle.forward(height)
    turtle.right(90)
    turtle.forward(width)
    turtle.right(90)
    turtle.forward(height)
    turtle.end_fill() 

turtle.reset()
turtle.speed(0)
#turtle.delay(0)
rect(-120, 160, 'gray', 120, -160)
rect(-75, 50, 'red', 75, -50)

turtle.penup()
turtle.goto(-25, 10)
turtle.pendown()
turtle.setheading(0)
turtle.pencolor("yellow")
turtle.fillcolor("yellow")
turtle.begin_fill()
for i in range(5):
    turtle.forward(50)
    turtle.right(144)
turtle.end_fill()
