import uturtle

turtle = uturtle.Turtle()

def rect(x, y, color, x2, y2):
    width = abs(x2 - x)
    height = abs(y2 - y)
    turtle.pencolor(color)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.fillcolor(color)
    # turtle.color(color, color)
    turtle.begin_fill()
    turtle.fd(width)
    turtle.right(90)
    turtle.forward(height)
    turtle.right(90)
    turtle.forward(width)
    turtle.right(90)
    turtle.forward(height)
    turtle.end_fill() 

turtle.reset()
turtle.speed(0)
#turtle.delay(0)
rect(-120, 160, 'gray', 120, -160)
rect(-72, 36, 'black', 72, 12)
rect(-72, 12, 'white', 72, -12)
rect(-72, -12, 'green', 72, -36)

turtle.penup()
turtle.goto(-27,0)
turtle.pendown()
turtle.begin_fill()
turtle.color('red', 'red')
turtle.goto(-72, 36)
turtle.goto(-72, -36)
turtle.goto(-27, 0)
turtle.end_fill()
